### ISSUE TITLE
Command results in "You dont have enough money to use this command" with the cost at 0

### ISSUE THREAD

**Issue by nightMue** [LuisSanchez-Dev/TheNewTTS#4]
Fresh install following the readme. With the "read all" option it works correctly but then the !tts command doesnt work as expected as it ignores anything with the '!'.  But if you dont have the "read all" option on and you use the !tts command if says you dont have enoght money to use this command even though the cost is set to 0.

**Comment by panoc** [comment]
@nightMue i have the same problem, here is a work around https://github.com/LuisSanchez-Dev/TheNewTTS/issues/7
